fix(/#80): AuthInterceptor implementation is incomplete
monstar-lab-oss/flutter-template pull request #91
Opened 2023-01-06 09:30 UTC by nivisi

Resolves #80 

---

Introduced:
- A new `Authenticator` class that is responsible for:
  - Making the tokens accessible by other classes such as interceptors. This class is the source of truth 
  - Trying to reauthenticate the user. The new interceptor, `ApiAuthInterceptor`, is using `Authenticator` to reauth if needed.
- A new `ApiAuthInterceptor` class. It is a rewritten version of the old interceptor — more readable and straightforward. This interceptor is a `QueuedInterceptor` now — meaning that, if we await for something, other request calls will wait until this call is resolved.

Both of the classes are covered with tests. If you think that not all the scenarios are covered — please let me know, I'll add those.

Also, we now use `FlutterSecureStorage` for storing the tokens. It is safer. **BUT**! This storage survives app uninstallation IIRC. So we should consider creating something that will detect fresh installation and clear the storage. Something like storing a value with the `freshInstallation` key in the shared prefs of the app.

2023-01-19 15:43 UTC, johsoe requested changes

2023-01-19 15:50 UTC, nivisi commented on lib/data/model/auth/auth_tokens.dart
>      required double expiresIn,
@johsoe in all the projects I've worked on we used `expiresIn`

2023-01-19 15:51 UTC, nivisi commented on lib/data/model/auth/auth_tokens.dart
>      required double expiresIn,
Do we use `expiresAt` on other projects?

2023-01-26 12:45 UTC, johsoe commented on lib/data/model/auth/auth_tokens.dart
>      required double expiresIn,
If that's the case, we should probably remove `expiresAt` - we shouldn't have both

2023-08-24 08:34 UTC, johsoe approved these changes

2024-10-22 12:55 UTC, closed without merging